name: Deploy Firebase Functions

on:
  push:
    branches:
      - main  # Deploy on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # Use a compatible Node.js version for Firebase CLI

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT_KEY > firebase-key.json
        firebase auth:activate-service-account --key-file=firebase-key.json

    - name: Navigate to Backend Directory
      working-directory: ./backend
      run: |
        npm install  # Install dependencies for the functions

    - name: Deploy Firebase Functions
      working-directory: ./backend
      env:
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
      run: |
        firebase deploy --only functions --project $FIREBASE_PROJECT
